services:
  - type: web
    name: whatsapp-gaming
    env: node
    buildCommand: npm install
    startCommand: node lib/app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
